[project]
name = "bambu-spoolman"
version = "0.1.0"
description = "Synchronize Bambu Lab printer filament usage with Spoolman"
authors = [
    { name = "mrkirby153", email = "mr.austinwhyte@gmail.com" },
    { name = "Joe Eversole", email = "joe@recompiled.org" },
]
requires-python = "~=3.14.0"
readme = "README.md"
dependencies = [
    "loguru>=0.7.3,<0.8",
    "requests>=2.34.2,<3",
    "python-dotenv>=1.2.2,<2",
    "paho-mqtt>=2.1.0,<3",
    "grpcio>=1.76.0",
    "protobuf>=6.33.5",
]

[project.scripts]
bambu-spoolman-broker = "bambu_spoolman.daemon:main"
mqtt-replay = "bambu_spoolman.debug.replay:main"

[dependency-groups]
dev = [
    "grpcio-tools>=1.76.0",
    "ruff==0.16.6",
    "setuptools>=83.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
extend-exclude = ["bambu_spoolman/grpc/*_pb2*"]

[tool.ruff.lint]
select = ["E", "F", "I"]
